# Generated by Django 3.2.7 on 2021-09-22 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_drivertrip_driverid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivertrip',
            old_name='DriverId',
            new_name='Driver',
        ),
    ]
