# Generated by Django 3.2.7 on 2021-10-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_alter_drivertrip_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertrip',
            name='Stops',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='Vacancy',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
