# Generated by Django 3.2.7 on 2021-10-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0007_auto_20211028_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivertrip',
            name='isTripStarted',
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='TripStatus',
            field=models.CharField(choices=[('0', 'Not Started'), ('1', 'Started'), ('2', 'Ended')], default=0, max_length=1),
        ),
    ]
