# Generated by Django 3.2.7 on 2021-10-29 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_drivertrip_profilepic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivertrip',
            old_name='profilepic',
            new_name='vehicleimg',
        ),
    ]
