# Generated by Django 3.2.7 on 2021-10-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0010_rename_profilepic_drivertrip_vehicleimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivertrip',
            name='vehicleimg',
            field=models.ImageField(upload_to='vimages/'),
        ),
    ]
