# Generated by Django 3.2.7 on 2021-10-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0011_alter_drivertrip_vehicleimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivertrip',
            name='vehicleimg',
            field=models.ImageField(default='image.jpg', upload_to='vimages/'),
        ),
    ]
