# Generated by Django 3.2.7 on 2021-10-25 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('city', '0002_auto_20210922_0027'),
        ('driver', '0006_auto_20211005_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOfSeatsBooked', models.IntegerField()),
                ('isTripComfirmed', models.BooleanField(default=False)),
                ('tripBookedOn', models.DateTimeField(auto_now=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.drivertrip')),
            ],
        ),
        migrations.CreateModel(
            name='BookRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination_City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_city', to='city.city')),
                ('Starting_City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_city', to='city.city')),
            ],
        ),
    ]
